[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://*.openstreetmap.org; style-src 'self'; base-uri 'self'; form-action 'self' https://www.google.com/maps/search/; frame-ancestors 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), camera=(), microphone=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"