[build]
  base = "hugo/"
  publish = "public/"
  command = "hugo -b $URL"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' data: https://*.openstreetmap.org; style-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), camera=(), microphone=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"