name: Archive full list

on:
  check_run:
    types: [completed]

jobs:
  archive:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Call archive webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.ARCHIVE_WEBHOOK_URL }}
          body: '{"event": "deployment"}'
